### PR TITLE
Add labels for new Hero Classes and pvp

### PR DESCRIPTION
**Pull request by Zelys-DFKH**

### CODE REVIEW

**Comment by thanpolas** [comment]
Hey @Zelys-DFKH, thank you very much for this. 

Since you are now casually contributing, would you mind following the codestyle of the project? In particular, project uses single quotes and not double quotes, which the CI should have caught but it hasn't triggered, which I now need to look into...

FYI The project is set to autoformat the code and take care of all these formatting arrangements if you edit via VSC and have the packages installed (`npm install`)

**Comment by thanpolas** [comment]
ah, it was only a setting I needed to enable on CircleCI, so next time you push it'll run the build and validate / lint the PR

**Comment by Zelys-DFKH** [comment]
Will do.  Sorry for the trouble

**Comment by thanpolas** [comment]
Hey @Zelys-DFKH, as you can see the CI still fails, you can click on the links to go and view why it fails... I am pasting a screenshot of the error for your convenience:

image

**Review by Zelys-DFKH — COMMENTED** [review]
Bard contained two different types of single quotes.  This has been enlightening!

**Comment by thanpolas** [comment]
There were still a few formatting issues, which got resolved by simply me saving the file and have auto-formatting take care of it (highly recommend to use auto-formatting so these issues won't creep up again).

And I also had to update all the unit tests that decoded the stat and visual genes of the hero ([more on this commit](https://github.com/degen-heroes/degenking/commit/3ea1394d5ad6ce6e1b252659d34cd60d8bbe8a20)).

Thank you for the contribution, the changes have been incorporated in the just published new version 1.4.13

**Pull request merged**
